---
title: "data2"
author: "Ziwei Crystal Zang"
date: "3/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readr)
library(haven)
library(data.table)
```

#Import Data
```{r}
#setwd("/Users/crystalzang/Desktop/data")


#individual
h16_R_all <- read_csv("~/Desktop/data/h16_R_all.csv")


#household
#h16_H_all <- read_csv("~/Desktop/HRS_SEM/h16_H_all.csv")


#Helper
helper<- read_sav("/Users/crystalzang/Desktop/data/spss/H16G_HP.sav", encoding = NULL, user_na = FALSE)



```


#Respondent file create id
```{r}
'%ni%' <- Negate('%in%')

class(h16_R_all$PPN_SP)

#filter out not valid id
h16_R_all_id <- h16_R_all%>%
  filter(!is.na(PPN_SP))%>%
  filter(PPN_SP %ni% c("811", "812", "821", "831", "832", "841", "822"))%>%
  mutate(respondent_id= paste(HHID, PN, sep=""), spouse_id=paste(HHID, PPN_SP, sep=""))

```

#Respondent file select variables
```{r}

h16_R_all_id <-h16_R_all_id %>%
  select(HHID, respondent_id, PN, spouse_id, PPN_SP, PG032_1, PG033_1, PG054_1,PG055_1, PZ260, PZ261, PZ262, PG016, PG021, PG023, PG025, PG030, PG014, PX060_R)


#Do we instead us PC? PC271,PC272,PC273 in section C: Physical Health (respondent)
setnames(h16_R_all_id ,
         old=c("PG032_1", "PG033_1", "PZ260", "PZ261", "PZ262", "PG016", "PG021", "PG023","PG025", "PG030", "PG014", "PX060_R"),
         new = c("WHO_HELPS_MOST_ADL_1", "ADL_HELPER_RELATIONSHIP_TO_R_1", "depression", "alzheimer","dementia", "ADL_walk", "ADL_shower", "ADL_eat", "ADL_bed", "ADL_toilet", "ADL_dress", "Sex.R"))

test <- table(h16_R_all_id$ADL_HELPER_RELATIONSHIP_TO_R_1, useNA = "a")

test <- table(respondent_ds$IADL_HELPER_RELATIONSHIP_TO_R_1, useNA = "a")


table(respondent_ds$dementia, useNA = "a")


#Filter out adl indicators missing
h16_R_all_adl<-h16_R_all_id %>%
  filter(ADL_walk %in% c(1,5), 
         ADL_shower %in% c(1,5),
         ADL_eat %in% c(1,5), 
         ADL_bed %in% c(1,5), 
         ADL_toilet %in% c(1,5), 
         ADL_dress %in% c(1,5))
```


#Join1: Helpers who were also respondents
```{r}
table(helper$PG074, useNA = "a")

helper <- helper%>%
  mutate(respondent_id= paste(HHID, PN, sep=""))%>%
  filter(!is.na(PPN_SP))%>%
  filter(PPN_SP %ni% c("","811", "812", "821", "831", "832", "841", "822"))%>%
  mutate(respondent_id= paste(HHID, PN, sep=""), spouse_id=paste(HHID, PPN_SP, sep=""))

test<-table(helper$PPN_SP)
test<-table(helper$spouse_id)


helper <- helper %>%
  select(HHID, respondent_id, PN, spouse_id, PPN_SP, PG069, PG070, PG074)


#Do we instead us PC? PC271,PC272,PC273 in section C: Physical Health (respondent)
setnames(helper ,
         old=c("PG069", "PG070", "PG074"),
         new = c("Helper_Relationship", "Freqency_help", "Helper_sex"))


#test <- left_join(helper, respondent_ds, by= c("helper_ID"="respondent_id"))%>%
#  filter(!is.na(HHID))

helper<- helper%>%
  filter(Helper_Relationship == "2")

helper_id<-helper%>%
  select(respondent_id, spouse_id, Helper_Relationship, Freqency_help, Helper_sex)

```

#Join1
```{r}
dyad <- left_join(h16_R_all_adl, helper_id, by = c("respondent_id"="spouse_id"))%>%
  mutate(respondent="Y",
         helper = if_else(Helper_Relationship == 2, "Y", "N"),
         resondent_and_helper= if_else(respondent=="Y" & helper=="Y", "Y", "N"))%>%
  mutate(identity = if_else(resondent_and_helper=="Y", "Resondent and helper", "Only respondent")) ##I have a bug here. I don't know why the alternative level"Only respondent" is not showing up here

                           
table(dyad$identity)

test<- dyad%>%
  group_by(respondent, helper, resondent_and_helper)%>%
  summarize(N=n())

class(dyad$Helper_Relationship)

#A dataset that contains all the helpers who are also respondents. Spouse_id is the helper's id. Respondent_id is their spouse's id. 
helper_and_respondent <- dyad %>%
  filter(helper== "Y")%>%
  mutate(Sex.H = Sex.R)


#respondent_only <- setdiff(dyad, helper_and_respondent)


#Prep dataset ready for join. Only include several variables
helper_and_respondent_id<-helper_and_respondent%>%
  select(respondent_id,spouse_id, helper)

#Join
#We want to find the mathcing respondents to our helpers
#Matching respondent_id (the people those helpers are helping) to the respondent in dyad data.
dyad_couple <- left_join(dyad, helper_also_respondent_id, by=c("spouse_id" ="respondent_id"))


#We are using both helper.x and helper.y to identify couples
#helper.x means help giver. help.y means help recipient.
dyad_couple <- dyad_couple%>%
  filter(helper.x=="Y" | helper.y =="Y")%>%
  select(-respondent_id.y)



#single people
test<-dyad_couple%>%
  group_by(HHID)%>%
  summarize(N=n())

```


#Join2: Helpers who were not respondents
```{r}
h16_R_all_adl_id<-h16_R_all_adl%>%
  select(respondent_id, Sex.R)

#match help recipients to their helpers
#helper_all <- left_join(helper_id, h16_R_all_adl_id, by ="respondent_id")
respondent_id <- setdiff(helper$respondent_id, helper_also_respondent$respondent_id)



#We want to set the difference between dyad_all with help_also_respondent to find those helpers who only helped but were not respondents.
#And then, we want to add them to our dyad.

helper_only_id <-as.data.frame(respondent_id)%>%
  mutate(identity="Helper_only")

helper_only2 <- left_join(helper, helper_only_id, by="respondent_id")%>%
  filter(identity=="Helper_only")
```

#Join2: Helpers who were not respondents
```{r}
##Join again
helper_only2_id<-helper_only2%>%
  select(spouse_id, Helper_Relationship, Freqency_help, Helper_sex)


dyad2 <- left_join(h16_R_all_adl, helper_only2_id, by ="spouse_id")%>%
  filter(Helper_Relationship==2)%>%
  mutate(respondent=NA,
         helper.x ="Y",
         helper.y = "N",
         resondent_and_helper= "N",
         identity = "Only helper")
        

```

#Combine 2 dyads
```{r}
dyad_complete <- rbind(dyad_couple, dyad2)

#single people
test<-dyad_complete%>%
  group_by(HHID)%>%
  summarize(N=n())

```
















############################################################
############################################################
#Tests

#Helper hour
```{r}
test<-helper%>%
  group_by(PG069, PPN_SP)%>%
  summarize(N=n())


test<-helper%>%
  group_by(respondent_id, PPN_SP)%>%
  summarise(N=n())
 
test_hh<- h16_R_all%>%
  mutate(respondent_id= paste(HHID, PN, sep=""))%>%
  group_by(HHID)%>%
  summarise(N=n())
```

#Helper
```{r}
helper_spouse <- helper%>%
  select(HHID,PN, PPN_SP, respondent_id, PG069, PADLNDX, PIADLNDX)%>%
  filter(PG069 == 2) #only spouse

setnames(helper_spouse,
         old=c("PG069", "PADLNDX", "PIADLNDX"),
         new = c("HELPER_RELATIONSHIP", "INDEX_ADL", "INDEX_IADL"))

table(helper_spouse$HELPER_RELATIONSHIP,useNA="a")
table(helper_spouse$INDEX_ADL,useNA="a")
table(helper_spouse$INDEX_IADL,useNA="a")

helper_valid <- helper_spouse%>%
  filter()
```










#Rename Variables
```{r}
test<-helper%>%
  group_by(HHID)%>%
  summarize(N=n())


setnames(helper, 
         old=c( "PN", "PPN_SP", "PFAMR", "OPN", "PG069", "PG066", "PADLNDX", "PIADLNDX", "PG070", "GP071", "PG072", "PG073", "PG074"),
          new=c("respondent_id", "helper_id", "whether_family_respondent", "other_person_number", "helper_relationship","who_helped_loop", "helper_ADL", "helper_IADL","freq_help", "days_help", "daily_help", "hours_help", "helper_sex"),  
         skip_absent=TRUE)

#No days_help

helper_edit <- helper %>%
  mutate(household_id = paste(HHID, PN, sep=""))%>%
  select(respondent_id, helper_id, whether_family_respondent, other_person_number, helper_relationship,who_helped_loop, helper_ADL, helper_IADL,freq_help, daily_help, hours_help, helper_sex)

View(helper_edit)


```


```{r}

respondent <- h16_R_all

setnames(respondent, 
         old = c("PC154","PC155","PC156", "PC157","PC158","PC159","PC160","PC161"),
         new = c("feeling_tired","lose_appetite","appetite_increase", "trouble_fall_asleep", "freq_trouble_fall_asleep", "trouble_concentrating", "feeling_down", "thoughts_about_death" ))


respondent <- respondent%>%
  select(feeling_tired,lose_appetite,appetite_increase,trouble_fall_asleep, freq_trouble_fall_asleep, trouble_concentrating, feeling_down, thoughts_about_death)
```


```{r}
H16G_R <- read_sav("/Users/crystalzang/Desktop/data/spss/H16G_R.sav", encoding = NULL, user_na = FALSE)%>%
  mutate(respondent_id = paste(HHID, PN, sep=""))
```

```{r}
test<-H16G_R%>%
  group_by(respondent_id)%>%
  summarize(N=n())

```

