---
title: "rand"
author: "CZ"
date: "3/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readr)
library(haven)
library(data.table)
library(ggplot2)
library(mosaic)
library(skimr)
```

```{r}
rand <- read_csv("~/Desktop/data/randhrs.csv")

#glimpse(rand)
```



```{r}
id <- rand %>%
  select(HHIDPN, HHID, PN, RAHHIDPN,
          R12CESD, S12CESD, #CESD Score, binary level yes or no
         
          R12ADLA, S12ADLA #ADL Summary: sum ADLs where Respondent reports any difficulty
        )

skim(id)

setnames(id ,
         old=c("R12ADLA", "S12ADLA", "R12CESD", "S12CESD"),
         new = c("R_ADL", "S_ADL", "R_CESD", "S_CESD"))

ggplot( data = id, aes(x = R_ADL)) + geom_histogram(binwidth = 1) + labs(title = "ADL respondent") 
ggplot( data = id, aes(x = S_ADL)) + geom_histogram(binwidth = 1) + labs(title = "ADL spouse") 

ggplot( data = id, aes(x = R_CESD)) + geom_histogram(binwidth = 1) + labs(title = "CESD respondent") 
ggplot( data = id, aes(x = S_CESD)) + geom_histogram(binwidth = 1) + labs(title = "CESD spouse") 

```

