---
title: "rand"
author: "CZ"
date: "3/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readr)
library(haven)
library(data.table)
library(ggplot2)
library(mosaic)
library(skimr)
```

```{r}
rand <- read_csv("~/Desktop/data/randhrs.csv")

#glimpse(rand)

```


#Extract variables and Data Exploration
```{r}
id <- rand %>%
  select(HHIDPN, HHID, PN, RAHHIDPN,
          R12CESD, S12CESD, #CESD Score, binary level yes or no
         
          R12ADLA, S12ADLA #ADL Summary: sum ADLs where Respondent reports any difficulty
        )

skim(id)
#rename
setnames(id ,
         old=c("R12ADLA", "S12ADLA", "R12CESD", "S12CESD"),
         new = c("R_ADL", "S_ADL", "R_CESD", "S_CESD"))

#filter out non-dyad individuals
id_valid <- id%>%
  filter(!is.na(R_ADL) | !is.na(S_ADL), !is.na(R_CESD), !is.na(S_CESD))

#There shouldn't be any missing R_ADL
tally(id_valid$S_ADL)

#Missing S_ADL meaning that those helper don't have ADL
tally(id_valid$S_ADL)

#There shouldn't be any missing R_CESD, we want all informaiton
tally(id_valid$R_CESD)

#There shouldn't be any missing S_CESD, we want all informaiton
tally(id_valid$S_CESD)

```

#Couple Investigation
```{r}
#check couple
id_group<-id_valid%>%
  group_by(HHID)%>%
  summarize(N=n())

#Only 2 is reasonable
tally(id_group$N)

#Valid dyad HHID 
id_valid_dyad_id <- id_group%>%
  filter(N==2)%>%
  select(HHID)%>%
  mutate(dyad = "Y")

#Cleaned dyad data
id_valid_dyad <- left_join(id_valid, id_valid_dyad_id, by="HHID")%>%
  filter(dyad == "Y")

write.csv(id_valid_dyad, file="rand_dyad.csv", row.names = F)
```

#Merge 2014 Helpers 
```{r}
helper_2014 <- read_sav("~/Desktop/data/H14G_HP.sav", encoding = NULL, user_na = FALSE)
rand_dyad <- read_csv("rand_dyad.csv")
```


```{r}
helper_2014 <- helper_2014 %>%
  filter(!is.na(OPN_SP))%>%
  filter(OPN_SP %ni% c("","811", "812", "821", "831", "832", "841", "822"))%>%
  mutate(respondent_id= paste(HHID, PN, sep=""), helper_id=paste(HHID, OPN_SP, sep=""))
```

```{r}
helper_2014 <- helper_2014 %>%
  select(HHID, respondent_id, PN, helper_id, OPN_SP, OG069, OG070,OG071,OG072,OG073)

helper_2014<- helper_2014%>%
  filter(OG069 == "2")
helper_2014 <- helper_2014 %>%
  mutate(HHIDPN=1000*as.numeric(HHID)+as.numeric(PN))

rand_dyad <- left_join(rand_dyad,helper_2014,by="HHIDPN")
```

##helping hours 
```{r}
helper_2014 <- read_sav("~/Desktop/data/H14G_HP.sav", encoding = NULL, user_na = FALSE)

```

```{r}
helper_2014 <- helper_2014 %>%
  filter(!is.na(OPN_SP))
#convert NA value in month/wk/day to 0 
helper_2014 <- helper_2014 %>%
  mutate(OG070 = coalesce(OG070,0),
         OG071 = coalesce(OG071,0),
         OG072 = coalesce(OG072,0),
         OG073 = coalesce(OG073,0))
#filter out useless values in month/wk/day/hr
helper_2014 <- helper_2014 %>%
  filter(OG070 %in% 0:31,
         OG071 %in% 0:7,
         OG072 %in% 0:1,
         OG073 %in% 1:24)

#calculate helping hours (assume that one month has 4 weeks and 30 days)
helper_2014 <- helper_2014 %>%
  mutate(helper_time = OG070*OG073+OG071*4*OG073+OG072*30*OG073)
```


