---
title: "rand"
author: "CZ"
date: "3/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readr)
library(haven)
library(data.table)
library(ggplot2)
library(mosaic)
library(skimr)
#functions
'%ni%' <- Negate('%in%')
```

```{r}
rand <- read_csv("~/Desktop/data/randhrs.csv")

#glimpse(rand)
#sample <- rand[sample(1:nrow(rand), 10,
#   replace=FALSE),]
```


#Extract variables and Data Exploration
R12... or S12... indicates 12 wave, which is from 2014. 
```{r}
id <- rand %>%
  select(HHIDPN, HHID, PN,
          R12CESD, S12CESD, #CESD Score, binary level yes or no
         
          R12ADLA, S12ADLA, #ADL Summary: sum ADLs where Respondent reports any difficulty
          R12OOPMD, S12OOPMD,  #Total expenditure
         RAGENDER
        )

skim(id)
#rename
setnames(id ,
         old=c("R12ADLA", "S12ADLA", "R12CESD", "S12CESD", "R12OOPMD", "S12OOPMD", "RAGENDER"),
         new = c("R_ADL", "S_ADL", "R_CESD", "S_CESD", "S_expense", "R_expense", "sex"))

#filter out non-dyad individuals
id_valid <- id%>%
  filter(!is.na(R_ADL), !is.na(S_ADL), !is.na(R_CESD), !is.na(S_CESD))

#There shouldn't be any missing R_ADL
tally(id_valid$S_ADL)

#Missing S_ADL meaning that those helper don't have ADL
tally(id_valid$S_ADL)

#There shouldn't be any missing R_CESD, we want all informaiton
tally(id_valid$R_CESD)

#There shouldn't be any missing S_CESD, we want all informaiton
tally(id_valid$S_CESD)
```

#Couple Investigation
```{r}
#check couple
id_group<-id_valid%>%
  group_by(HHID)%>%
  summarize(N=n())

#Only 2 is reasonable
tally(id_group$N)

#Valid dyad HHID 
id_valid_dyad_id <- id_group%>%
  filter(N==2)%>%
  select(HHID)%>%
  mutate(dyad = "Y")

#Cleaned dyad data
id_valid_dyad <- left_join(id_valid, id_valid_dyad_id, by="HHID")%>%
  filter(dyad == "Y")

#write.csv(id_valid_dyad, file="rand_dyad.csv", row.names = F)
```

#Read dyad data seperately
```{r}
id_valid_dyad   <-read_csv("rand_dyad.csv") 

```


# Helper READ IN
```{r}
#year: 2016
helper <- read_sav("/Users/crystalzang/Desktop/data/helper/H14G_HP.sav", encoding = NULL, user_na = FALSE)%>%
  filter(!is.na(OPN_SP))%>%
  filter(OPN_SP %ni% c("","811", "812", "821", "831", "832", "841", "822"))%>%
  mutate(respondent_id= paste(HHID, PN, sep=""), spouse_id=paste(HHID, OPN_SP, sep=""))%>%
  filter(OG069 == "2")

#convert NA value in month/wk/day to 0 
helper<- helper %>%
  mutate(OG070 = coalesce(OG070,0),
         OG071 = coalesce(OG071,0),
         OG072 = coalesce(OG072,0),
         OG073 = coalesce(OG073,0))
#filter out useless values in month/wk/day/hr
helper <- helper %>%
  filter(OG070 %in% 0:31,
         OG071 %in% 0:7,
         OG072 %in% 0:1,
         OG073 %in% 1:24)

#calculate helping hours (assume that one month has 4 weeks and 30 days)
helper <-helper%>%
  mutate(helper_time = OG070*OG073+OG071*4*OG073+OG072*30*OG073)

helper_id <- helper%>%
  select(respondent_id, spouse_id, helper_time) %>% 
  mutate(helper="Y")
```


```{r eval=FALSE, include=FALSE}
#plot helper hours
ggplot(data=helper_2014, aes(x=helper_time))+geom_histogram()
count(helper_2014$helper_time==1)

table(helper$OG073)

test <- helper%>%
  group_by(OG070, OG073)%>%
  summarize(N=n())
```


# Create sub-dataset by helper status
```{r}
#Join helper with spouse in RAND, indicating spouses who are helpers
class(id_valid_dyad$HHIDPN)
class(helper_id$respondent_id)
id_valid_dyad$HHIDPN<-as.character(id_valid_dyad$HHIDPN)

helper <- left_join(id_valid_dyad, helper_id, by= c("HHIDPN"= "respondent_id"))%>%
  filter(helper=="Y")%>%
  mutate(helper_status = "helper")

```

# Type 1 Both helper
```{r}
#check couple
dyad_helper_both<-helper%>%
  group_by(HHID)%>%
  mutate(N=n())%>%
  filter(N==2)
```



# Type 2 Women helper
```{r}
helper_f <- helper %>%
  filter(sex=="2.Female")

helper_f_id<-helper_f%>%
  select(spouse_id)%>%
  as.data.frame()

helper_f_spouse <- left_join(helper_f_id, id_valid_dyad , by= c("spouse_id" = "HHIDPN"))%>%
  mutate(helper_status = "not helper", helper_time = 0)

names(helper_f_spouse)[1]<- "HHIDPN"
helper_f<- helper_f%>%
  select(-spouse_id, -helper)

dyad_helper_f <- rbind(helper_f, helper_f_spouse)
write.csv(dyad_helper_f, file="dyad_helper_f.csv", row.names = F)

```


```{r}
helper_m <- helper %>%
  filter(sex=="1.Male")

helper_m_id<-helper_m%>%
  select(spouse_id)%>%
  as.data.frame()

helper_m_spouse <- left_join(helper_m_id, id_valid_dyad , by= c("spouse_id" = "HHIDPN"))%>%
  mutate(helper_status = "not helper", helper_time = 0)

names(helper_m_spouse)[1]<- "HHIDPN"
helper_m<- helper_m%>%
  select(-spouse_id, -helper)

dyad_helper_m <- rbind(helper_m, helper_m_spouse)
write.csv(dyad_helper_m, file="dyad_helper_m.csv", row.names = F)

```



