---
title: "rand_dyad"
author: "CZ"
date: "3/26/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(readr)
library(haven)
library(data.table)
library(ggplot2)
library(mosaic)
library(skimr)
```

```{r}
rand_dyad <- read_csv("rand_dyad.csv")
```
# Three dyads

## 1. Both respondent and helper
```{r}
dyad_1 <- rand_dyad%>%
  filter(R_ADL >0 & S_ADL>0)

test <- dyad_1%>%
  group_by(R_ADL, S_ADL)%>%
  summarize(N=n())

```



## 2. Helper don't have ADL
```{r}
dyad_2 <- setdiff(rand_dyad, dyad_1, by=HHIDPN)%>%
  filter(!is.na(R_ADL), !is.na(S_ADL))

test <- dyad_2%>%
  group_by(R_ADL, S_ADL)%>%
  summarize(N=n())
```



#Variable Investigation
```{r}
test <- rand_dyad%>%
  group_by(R_ADL, S_ADL)%>%
  summarize(N=n())


ggplot( data = id_valid_dyad, aes(x = R_ADL)) + geom_histogram(binwidth = 1) + labs(title = "ADL respondent") 
ggplot( data = id_valid_dyad, aes(x = S_ADL)) + geom_histogram(binwidth = 1) + labs(title = "ADL spouse") 

ggplot( data = id_valid_dyad, aes(x = R_CESD)) + geom_histogram(binwidth = 1) + labs(title = "CESD respondent") 
ggplot( data = id_valid_dyad, aes(x = S_CESD)) + geom_histogram(binwidth = 1) + labs(title = "CESD spouse") 

```

#path analysis for basic model
```{r}
model_1 <- '
            R_CESD~R_ADL
            S_CESD~S_ADL
            R_CESD ~~ S_CESD
      '
fit_1 <- sem(model_1, data = rand_dyad)
summary(fit_1,standardized = TRUE, fit.measures = TRUE)
library(semPlot)
semPaths(fit_1,rotation=2)
```

#transformation

```{r}
scale_exp <- scale(dyad_female_helper$expenditure, center = TRUE, scale = TRUE)
ggplot(data=dyad_female_helper,aes(x=scale_exp))+geom_histogram()
```

```{r}
#change ADL to cognitive score 
female_helper <- read_csv("~/Desktop/HRS_SEM_2019/data/dyad_helper_f.csv")
```



```{r}
female_helper<- female_helper%>%
  mutate(S_self_health = if_else(S_self_health == "1.Excellent", 1,
                         if_else(S_self_health == "2.Very good", 2,
                         if_else(S_self_health == "3.Good", 3,
                         if_else(S_self_health == "4.Fair", 4,5)))))%>%
  mutate(R_self_health = if_else(R_self_health == "1.Excellent", 1,
                         if_else(R_self_health == "2.Very good", 2,
                         if_else(R_self_health == "3.Good", 3,
                         if_else(R_self_health == "4.Fair", 4,5))))) %>%
  mutate(R_self_health_change = if_else(R_self_health_change  == "2.Somewhat better", 0,
                                if_else(R_self_health_change == "3.Same", 1, 2)))%>%
  mutate(S_self_health_change = if_else(S_self_health_change=="2.Somewhat better", 0,
                                if_else(S_self_health_change == "3.Same", 1, 2)))%>%
  mutate(R_drug =if_else(R_drug == "1.Yes", 1, 0)) %>%
  mutate(S_drug =if_else(S_drug == "1.Yes", 1, 0)) %>%
  mutate(R_surgery =if_else(R_surgery == "1.Yes", 1, 0)) %>%
  mutate(S_surgery=if_else(S_surgery == "1.Yes", 1, 0)) %>%
  mutate(R_special_hservice=if_else(R_special_hservice == "1.Yes", 1, 0)) %>%
  mutate(S_special_hservice=if_else(S_special_hservice == "1.Yes", 1, 0))  %>%
  filter(sex=="2.Female")%>%   ### Change gender here 
  filter(R_ADL>0)%>%
#  filter(HHIDPN != 204936010) %>%
  mutate(expenditure=S_expense+R_expense) %>%
  mutate(S_exp.z=scale(S_expense, center = TRUE, scale = TRUE)) %>%
  mutate(R_exp.z=scale(R_expense, center = TRUE, scale = TRUE)) %>%
  mutate(exp.z=scale(expenditure, center = TRUE, scale = TRUE)) %>%
  mutate(hhour.z=scale(helper_time,center=TRUE,scale=TRUE))%>%
  mutate(R_income_i.z = scale(R_income_i,center=TRUE,scale=TRUE))%>%
 mutate(S_income_i.z = scale(S_income_i,center=TRUE,scale=TRUE))%>%
  mutate(R_hostital_stay.z = scale(R_hostital_stay,center=TRUE,scale=TRUE)) 
```

```{r}
%>%
  mutate(R_ADL_binary = if_else(R_ADL > 0, 1, 0))%>%
  mutate(optimism_B_r = 7 - optimism_B,
         optimism_C_r = 7 - optimism_C,
         optimism_D_r = 7 - optimism_D)%>%
  mutate(
         sp_eqD_r = 5 - sp_eqD,
         sp_eqE_r = 5 - sp_eqE,
         sp_eqF_r = 5 - sp_eqF,
         sp_eqG_r = 5 - sp_eqG)
```



```{r}
model_f <- '
            S_CESD ~ S_self_health + S_ADL + S_cog_score + R_self_health
            R_CESD ~ S_self_health  + R_cog_score + R_self_health 
            S_self_health ~ S_ADL
            R_self_health ~ R_ADL
            S_ADL ~ S_cog_score
            R_ADL ~  R_cog_score
            S_CESD ~~ R_CESD  '

fit_f <- sem(model_f, data = female_helper, estimator="MLMV")


varTable(fit_f)
summary(fit_f,standardized = TRUE, fit.measures = TRUE)
library(semPlot)
semPaths(fit_f)

female_helper <- female_helper %>%
  select(R_ADL, S_ADL, S_self_healh, R_self_health, S_CESD, R_CESD)
cor = cor(female_helper)
```

```{r}
male_helper_psych <- read_csv("~/Desktop/HRS_SEM_2019/data/dyad_helper_m_psych.csv")
male_helper_psych<- male_helper_psych%>%
  mutate(S_self_health = if_else(S_self_health == "1.Excellent", 1,
                         if_else(S_self_health == "2.Very good", 2,
                         if_else(S_self_health == "3.Good", 3,
                         if_else(S_self_health == "4.Fair", 4,5)))))%>%
  mutate(R_self_health = if_else(R_self_health == "1.Excellent", 1,
                         if_else(R_self_health == "2.Very good", 2,
                         if_else(R_self_health == "3.Good", 3,
                         if_else(R_self_health == "4.Fair", 4,5))))) %>%
  mutate(R_self_health_change = if_else(R_self_health_change  == "2.Somewhat better", 0,
                                if_else(R_self_health_change == "3.Same", 1, 2)))%>%
  mutate(S_self_health_change = if_else(S_self_health_change=="2.Somewhat better", 0,
                                if_else(S_self_health_change == "3.Same", 1, 2)))%>%
  mutate(R_drug =if_else(R_drug == "1.Yes", 1, 0)) %>%
  mutate(S_drug =if_else(S_drug == "1.Yes", 1, 0)) %>%
  mutate(R_surgery =if_else(R_surgery == "1.Yes", 1, 0)) %>%
  mutate(S_surgery=if_else(S_surgery == "1.Yes", 1, 0)) %>%
  mutate(R_special_hservice=if_else(R_special_hservice == "1.Yes", 1, 0)) %>%
  mutate(S_special_hservice=if_else(S_special_hservice == "1.Yes", 1, 0))  %>%
  filter(sex=="2.Female")%>%   ### Change gender here 
  filter(R_ADL>0)%>%
  mutate(expenditure=S_expense+R_expense) %>%
  mutate(S_exp.z=scale(S_expense, center = TRUE, scale = TRUE)) %>%
  mutate(R_exp.z=scale(R_expense, center = TRUE, scale = TRUE)) %>%
  mutate(exp.z=scale(expenditure, center = TRUE, scale = TRUE)) %>%
  mutate(hhour.z=scale(helper_time,center=TRUE,scale=TRUE))%>%
  mutate(R_income_i.z = scale(R_income_i,center=TRUE,scale=TRUE))%>%
 mutate(S_income_i.z = scale(S_income_i,center=TRUE,scale=TRUE))%>%
  mutate(R_hostital_stay.z = scale(R_hostital_stay,center=TRUE,scale=TRUE)) %>%
  mutate(R_ADL_binary = if_else(R_ADL > 0, 1, 0))%>%
  mutate(optimism_B_r = 7 - optimism_B,
         optimism_C_r = 7 - optimism_C,
         optimism_D_r = 7 - optimism_D)%>%
  mutate(
         sp_eqD_r = 5 - sp_eqD,
         sp_eqE_r = 5 - sp_eqE,
         sp_eqF_r = 5 - sp_eqF,
         sp_eqG_r = 5 - sp_eqG)
```


```{r}
model_m <- '
            S_CESD ~ S_self_health + S_ADL + S_cog_score + R_self_health
            R_CESD ~ S_self_health  + R_cog_score + R_self_health 
            S_self_health ~ S_ADL
            R_self_health ~ R_ADL
            S_ADL ~ S_cog_score
            R_ADL ~  R_cog_score
            S_CESD ~~ R_CESD  '

fit_m <- sem(model_m, data = male_helper_psych, estimator="MLMV")


varTable(fit_m)
summary(fit_m,standardized = TRUE, fit.measures = TRUE)
library(semPlot)
semPaths(fit_m)
```




```{r}

model_f <- '
            S_CESD ~ S_cog_score + exp.z + exp.z+R_cog_score + S_health_condition + R_health_condition 
            R_CESD ~ R_cog_score + hhour.z + exp.z+S_cog_score + S_health_condition + R_health_condition 
            hhour.z~R_cog_score + S_cog_score
            exp.z~R_cog_score + S_cog_score
            S_health_condition~R_cog_score + S_cog_score
             R_health_condition ~R_cog_score + S_cog_score
        '
fit_f <- sem(model_f, data = female_helper_psych,estimator="MLMV")
summary(fit_f,standardized = TRUE, fit.measures = TRUE)
library(semPlot)
semPaths(fit_f)

```


```{r}
#why NA in standard error 
#why mod indice is not working 
#how to adjust estimator in the model: subscript out of bounds

library(lavaan)
dyad_helper_f <- read_csv("data/dyad_helper_f.csv")
dyad_female_helper <- dyad_helper_f %>%
  filter(sex=="2.Female") %>%
#  filter(R_ADL!=0) %>%
 # mutate(expenditure=S_expense+R_expense) %>%
  mutate(scale_exp=scale(R_expense, center = TRUE, scale = TRUE)) %>%
  mutate(scale_help=scale(helper_time,center=TRUE,scale=TRUE))
#basic model
model_f <- '
            S_CESD ~ S_ADL + scale_help + scale_exp+R_ADL
            R_CESD ~ R_ADL + scale_help + scale_exp+S_ADL
            scale_help~R_ADL + S_ADL
            scale_exp~R_ADL + S_ADL      '
```




```{r}
#estimator = MLM?
fit_f <- sem(model_f, data = dyad_female_helper,estimator="MLMV")
modindices(fit_f) %>% 
  arrange(desc(mi)) %>%
  select(lhs, op, rhs, mi) %>%
  head(10)
varTable(fit_f)
summary(fit_f,standardized = TRUE, fit.measures = TRUE)
library(semPlot)
semPaths(fit_f)
```
```{r}
dyad_helper_f <- read_csv("data/dyad_helper_f.csv")
dyad_female_helper <- dyad_helper_f %>%
  filter(sex=="2.Female") %>%
#  filter(R_ADL!=0) %>%
 # mutate(expenditure=S_expense+R_expense) %>%
  mutate(scale_exp=scale(R_expense, center = TRUE, scale = TRUE)) %>%
  mutate(scale_help=scale(helper_time,center=TRUE,scale=TRUE))
#basic model
model_f_2 <- '
            S_CESD ~ S_ADL + scale_help + scale_exp
            R_CESD ~ R_ADL + scale_help + scale_exp
            scale_help~R_ADL + S_ADL
            scale_exp~R_ADL + S_ADL
      '
#estimator = MLM?
fit_f_2 <- sem(model_f_2, data = dyad_female_helper,estimator="MLMV")
summary(fit_f_2,standardized = TRUE, fit.measures = TRUE)
library(semPlot)
semPaths(fit_f_2)
```


```{r}
dyad_helper_m <- read_csv("data/dyad_helper_m.csv")
dyad_male_helper <- dyad_helper_m %>%
  filter(sex=="1.Male") %>%
 # mutate(expenditure=S_expense+R_expense) %>%
  mutate(scale_exp=scale(R_expense, center = TRUE, scale = TRUE)) %>%
  mutate(scale_help=scale(helper_time,center=TRUE,scale=TRUE))

#basic model
model_m <- '
            S_CESD ~ S_ADL + scale_help + scale_exp
            R_CESD ~ R_ADL + scale_help + scale_exp
            scale_help~R_ADL + S_ADL
            scale_exp~R_ADL + S_ADL   
      '
#estimator = MLM?
fit_m <- sem(model_m, data = dyad_male_helper)
varTable(fit_m)
summary(fit_m,standardized = TRUE, fit.measures = TRUE)
semPaths(fit_m)
```



```{r}
ggplot(aes(x=S_CESD),data=dyad_female_helper)+geom_histogram(bins = 8)
```

```{r}
dyad_all <- read_csv("data/dyad_all.csv")
dyad_male_helper <- dyad_helper_m %>%
  filter(helper_status=="helper") %>%
 # mutate(expenditure=S_expense+R_expense) %>%
  mutate(scale_exp=scale(R_expense, center = TRUE, scale = TRUE)) %>%
  mutate(scale_help=scale(helper_time,center=TRUE,scale=TRUE))

#basic model
model_all <- '
            S_CESD ~ S_ADL + scale_help + scale_exp
            R_CESD ~ R_ADL + scale_help + scale_exp
            scale_help~R_ADL + S_ADL
            scale_exp~R_ADL + S_ADL   
      '
#estimator = MLM?
fit_all <- sem(model_m, data = dyad_male_helper, estimator="MLMVS")
summary(fit_all,standardized = TRUE, fit.measures = TRUE)
semPaths(fit_all)
```

