---
title: "rand_dyad"
author: "CZ"
date: "3/26/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(ggplot2)
library(lavaan)
library(semPlot)
```

```{r}
dyad_helper_f <- read_csv("data/dyad_helper_f.csv")
dyad_helper_m <- read_csv("data/dyad_helper_m.csv")

```
# Two dyads
## 1. Both respondent and helper
```{r}
dyad_1 <- rand_dyad%>%
  filter(R_ADL >0 & S_ADL>0)

test <- dyad_1%>%
  group_by(R_ADL, S_ADL)%>%
  summarize(N=n())

```



## 2. Helper don't have ADL
```{r}
dyad_2 <- setdiff(rand_dyad, dyad_1, by=HHIDPN)%>%
  filter(!is.na(R_ADL), !is.na(S_ADL))

test <- dyad_2%>%
  group_by(R_ADL, S_ADL)%>%
  summarize(N=n())
```



#Variable Investigation
```{r}
test <- dyad_helper_f%>%
  group_by(R_ADL, S_ADL)%>%
  summarize(N=n())


ggplot( data = id_valid_dyad, aes(x = R_ADL)) + geom_histogram(binwidth = 1) + labs(title = "ADL respondent") 
ggplot( data = id_valid_dyad, aes(x = S_ADL)) + geom_histogram(binwidth = 1) + labs(title = "ADL spouse") 

ggplot( data = id_valid_dyad, aes(x = R_CESD)) + geom_histogram(binwidth = 1) + labs(title = "CESD respondent") 
ggplot( data = id_valid_dyad, aes(x = S_CESD)) + geom_histogram(binwidth = 1) + labs(title = "CESD spouse") 

```


```{r}
dyad_female_helper <- dyad_helper_f %>%
  filter(sex=="2.Female")%>%
  filter(R_ADL>0)%>%
  filter(HHIDPN != 204936010) %>%
  mutate(expenditure=S_expense+R_expense) %>%
  mutate(exp.z=scale(expenditure, center = TRUE, scale = TRUE)) %>%
  mutate(hhour.z=scale(helper_time,center=TRUE,scale=TRUE))

#basic model--cesd covariate
model_f <- '
            S_CESD ~ S_ADL +  hhour.z + exp.z
            R_CESD ~ R_ADL + hhour.z + exp.z 
            hhour.z~R_ADL + S_ADL
            exp.z~R_ADL + S_ADL   
            S_ADL ~~  R_ADL
            S_CESD ~~ R_CESD
      '

fit_f <- sem(model_f, data = dyad_female_helper)
varTable(fit_f)
summary(fit_f,standardized = TRUE, fit.measures = TRUE)
library(semPlot)
semPaths(fit_f)


#CFA
#fit_f_cfa <- cfa(model_f, data=dyad_female_helper, estimator)


#model2 -- cesd direct affect (R_CESD --> S_CESD)
model_f <- '
            S_CESD ~ S_ADL +  hhour.z + exp.z + R_CESD
            R_CESD ~ R_ADL + hhour.z + exp.z 
            hhour.z~R_ADL + S_ADL
            exp.z~R_ADL + S_ADL   
            S_ADL ~~  R_ADL
      '

fit_f <- sem(model_f, data = dyad_female_helper)
varTable(fit_f)
summary(fit_f,standardized = TRUE, fit.measures = TRUE)
library(semPlot)
semPaths(fit_f)


#model3 -- cesd direct affect (R_CESD <--> S_CESD)
model_f <- '
            S_CESD ~ S_ADL +  hhour.z + exp.z + R_CESD
            R_CESD ~ R_ADL + hhour.z + exp.z + S_CESD
            hhour.z~R_ADL + S_ADL
            exp.z~R_ADL + S_ADL   
            S_ADL ~~  R_ADL
      '

fit_f <- sem(model_f, data = dyad_female_helper)
varTable(fit_f)
summary(fit_f,standardized = TRUE, fit.measures = TRUE)
library(semPlot)
semPaths(fit_f)

#model4 -- cesd direct affect (R_CESD <-- S_CESD)
model_f <- '
            S_CESD ~ S_ADL +  hhour.z + exp.z 
            R_CESD ~ R_ADL + hhour.z + exp.z + S_CESD
            hhour.z~R_ADL + S_ADL
            exp.z~R_ADL + S_ADL   
            S_ADL ~~  R_ADL
      '

fit_f <- sem(model_f, data = dyad_female_helper)
varTable(fit_f)
summary(fit_f,standardized = TRUE, fit.measures = TRUE)
library(semPlot)
semPaths(fit_f)

```

```{r}

dyad_male_helper <- dyad_helper_m %>%
  filter(sex=="1.Male") %>%
  filter(R_ADL>0)%>%
  filter(HHIDPN != 204936010) %>%
  mutate(expenditure=S_expense+R_expense) %>%
  mutate(exp.z=scale(expenditure, center = TRUE, scale = TRUE)) %>%
  mutate(hhour.z=scale(helper_time,center=TRUE,scale=TRUE))

#basic model
model_m <- '
            S_CESD ~ S_ADL +  hhour.z + exp.z
            R_CESD ~ R_ADL + hhour.z + exp.z 
            hhour.z~R_ADL + S_ADL
            exp.z~R_ADL + S_ADL 
            S_ADL ~~  R_ADL
            S_CESD ~~ R_CESD
      '

fit_m <- sem(model_m, data = dyad_male_helper)

varTable(fit_m)

summary(fit_m,standardized = TRUE, fit.measures = TRUE)
library(semPlot)
semPaths(fit_m)


#model2 -- cesd direct affect (R_CESD --> S_CESD)
model_m <- '
            S_CESD ~ S_ADL +  hhour.z + exp.z + R_CESD
            R_CESD ~ R_ADL + hhour.z + exp.z 
            hhour.z~R_ADL + S_ADL
            exp.z~R_ADL + S_ADL   
            S_ADL ~~  R_ADL
      '

fit_m <- sem(model_m, data = dyad_male_helper)
varTable(fit_m)
summary(fit_m,standardized = TRUE, fit.measures = TRUE)
library(semPlot)
semPaths(fit_m)


#model3 -- cesd direct affect (R_CESD <--> S_CESD)
model_m  <- '
            S_CESD ~ S_ADL +  hhour.z + exp.z + R_CESD
            R_CESD ~ R_ADL + hhour.z + exp.z + S_CESD
            hhour.z~R_ADL + S_ADL
            exp.z~R_ADL + S_ADL   
            S_ADL ~~  R_ADL
      '
fit_m <- sem(model_m, data = dyad_male_helper)
varTable(fit_m)
summary(fit_m,standardized = TRUE, fit.measures = TRUE)
library(semPlot)
semPaths(fit_m)


#model4 -- cesd direct affect (R_CESD <-- S_CESD)
model_m <- '
            S_CESD ~ S_ADL +  hhour.z + exp.z 
            R_CESD ~ R_ADL + hhour.z + exp.z + S_CESD
            hhour.z~R_ADL + S_ADL
            exp.z~R_ADL + S_ADL   
            S_ADL ~~  R_ADL
      '
fit_m <- sem(model_m, data = dyad_male_helper)
varTable(fit_m)
summary(fit_m,standardized = TRUE, fit.measures = TRUE)
library(semPlot)
semPaths(fit_m)
```

