---
title: "data_psych_CZ"
author: "CZ"
date: "4/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readr)
library(haven)
library(data.table)
library(ggplot2)
library(mosaic)
library(skimr)
#functions
'%ni%' <- Negate('%in%')
library(haven)
library(data.table)
```

```{r}
psych<- read_sav("~/Desktop/data/H14LB_R.sav", encoding = NULL, user_na = FALSE)
dyad_helper_f <- read_csv("data/dyad_helper_f.csv")


dyad_helper_m <- read_csv("data/dyad_helper_m.csv")
```

```{r}
head(psych)

psych_data1 <- psych %>%
  select(HHID,PN,OPN_SP,OLB018A,OLB018B,OLB018C,OLB018D,OLB018E,OLB018F,OLB018G,OLB018H,OLB018I,OLB018J, OLB004A,OLB004B,OLB004C,OLB004D,OLB004E,OLB004F,OLB004G,OLB005, OLB005A, OLB005B)

psych_data1 $HHID<- as.numeric(psych_data1 $HHID)
psych_data1 $PN<- as.numeric(psych_data1 $PN)
psych_data1 $OPN_SP<- as.numeric(psych_data1 $OPN_SP)

psych_data2<- psych_data1%>%
  filter(!is.na(OPN_SP))%>%
  filter(OPN_SP %ni% c("","811", "812", "821", "831", "832", "841", "822"))%>%
#  mutate(respondent_id= paste(HHID, PN, sep=""), spouse_id=paste(HHID, OPN_SP, sep=""))
  mutate(respondent_id= 1000*HHID + PN, spouse_id=1000*HHID + OPN_SP)

setnames(psych_data2 ,
         old=c("OLB018A","OLB018B","OLB018C","OLB018D","OLB018E","OLB018F","OLB018G","OLB018H","OLB018I","OLB018J",
               "OLB004A","OLB004B","OLB004C","OLB004D","OLB004E","OLB004F","OLB004G",
               "OLB005", "OLB005A", "OLB005B"
               ),
         
         new = c("optimism_A", "optimism_B", "optimism_C","optimism_D", "optimism_E","optimism_F","optimism_G","optimism_H","optimism_I","optimism_J",
                 "sp_eqA", "sp_eqB", "sp_eqC","sp_eqD","sp_eqE", "sp_eqF", "sp_eqG",
                 "sp_relation", "sp_relationA", "sp_relationB"
                ))

#write.csv(psych_data2, file= "psych_data.csv")
```


```{r}
dyad_helper_f_psy <- left_join(dyad_helper_f, psych_data2, by=c("HHIDPN" = "respondent_id"))
write.csv(dyad_helper_f_psy, file= "data/dyad_helper_f_psych.csv")

dyad_helper_m_psy <- left_join(dyad_helper_m, psych_data2, by=c("HHIDPN" = "respondent_id"))
write.csv(dyad_helper_m_psy, file= "data/dyad_helper_m_psych.csv")


```



